#!/usr/bin/env bash

#ddev-generated
## Description: Run Spidergram inside the web container
## Usage: spidergram [flags] [args]
## Example: "spidergram help" or "spidergram status"
## ExecRaw: true

spidergram "$@"